### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by erictsai1208**

### CODE REVIEW

**Review by zchen156 — APPROVED** [review]
Reviewed & Approve

**Review by ranjitprakash1986 — COMMENTED** [review]
Hi Eric, thanks for these updates to Readme, it looks great. One think I noticed is that my name appears twice and Tanmay's name is missing

**Comment by erictsai1208** [comment]
Ahh I was not paying attention when I copy-pasted. I'll fix that when I add to the readme the functions we will write.

**Comment by erictsai1208** [comment]
Addresses #14

**Pull request merged**
